const lookup = {
  0: "noun phrase, a",
  1: "noun phrase, h",
  2: "noun phrase, t",
  3: "noun phrase, p",
  4: "noun phrase, d",
  5: "noun phrase, w",
  // 6: "noun phrase prep, a",
  7: "noun phrase prep, h",
  // 8: "noun phrase prep, t",
  9: "noun phrase prep, p",
  10: "noun phrase prep, d",
  11: "noun phrase prep, w",
  12: "verb phrase",
  13: "verb phrase prep",
  14: "adverb",
  15: "adjective",
  16: "adjective phrase",
  17: "transitive verb",
  18: "intransitive verb",
  19: "dialogue phrase",
};
const genders = [
  [
    ["he", "she"],
    ["his", "her"],
    ["his", "hers"],
    ["him", "her"],
    ["man", "woman"],
  ],
  [
    ["I", "you"],
    ["my", "your"],
    ["mine", "yours"],
    ["me", "you"],
    ["person", "friend"],
  ],
];
const tags = [
  [
    // 6: "noun phrase, a",
    `for my heart now too is dyin!`,
    `to serve out my time`,
    `your farewell to ^g4`,
    `the doctor came`,
    `the dead began to speak`,
    `through desire and death`,
    `with my dying breath`,
    `for twenty-one year`,
    `^g1 knew that ^g1o would drown`,
    `no ^g5o may know`,
    `^g2o head was found in the drivin' wheel`,
    `a tear trinkled down`,
    `^g1 can't keep a good one down`,
  ],
  [
    // 7: "noun phrase, h",
    `a jealous lover`,
    `a beautiful maid`,
    `the governor`,
    `two boys`,
    `a hundred seamen`,
    `the jealous lover`,
    `the beautiful girl`,
    `the people`,
    `the eskimo`,
    `young folks`,
    `her father`,
    `the only child`,
    `a gypsy queen`,
    `Charlie`,
    `Charlotte`,
    `the prettiest girl`,
    `Evaline`,
    `a long tall mama`,
    `a sweet little woman`,
    `the doctors son`,
    `my sweetest love`,
    `poor William`,
    `the judge`,
    `John Lewis`,
    `Omie Wise`,
    `Stagolee`,
    `young Charlotte`,
    `m'love`,
    `^g2 sweetest love`,
    `^g2 true love`,
    `the gypsy`,
    `the servant`,
    `the no-future priestess`,
    `the Christian saints`,
  ],
  [
    // 8: "noun phrase, t",
    `^g2 pale corpse`,
    `^g2o pale corpse`,
    `a red rose and a briar`,
    `a briar`,
    `^g2 six shooter`,
    `the stars`,
    `the night`,
    `the birds`,
    `the fatal knife`,
    `the steam from the whistle`,
    `the smoke from the stack`,
    `best friends`,
    `the days`,
    `the nights`,
    `the minutes`,
    `the footsteps`,
    `the stars`,
    `prison bars`,
    `other fine things`,
    `the screams of little Omie`,
    `cruel hardships`,
    `the fate of franklin`,
    `my burden`,
    `my long-lost franklin`,
    `a suit of clothes`,
    `the sun`,
    `bright blue eyes`,
    `^g2o heart`,
    `the sleigh`,
    `^g2 silken coat`,
    `The cloak and bonnet`,
    `the frozen snow`,
    `the frozen air`,
    `these frozen words`,
    `the silence`,
    `the frosty ice`,
    `the frosty air`,
    `the glittering cold starlight`,
    `^g2o hand`,
    `the cold stars`,
    `^g2 frozen corpse`,
    `^g2o frozen corpse`,
    `the bitter tears`,
    `^g2 thoughts`,
    `the train`,
    `that train`,
    `the long steel rail`,
    `^g2 transportation`,
    `the headlights`,
    `the dead`,
    `a bottle of wine`,
    `^g2 old grey steed`,
    `the water`,
    `yellow street lamps`,
    `a band of gypsies`,
    `the empty vessels of Berlin youth`,
    `a crown of blood`,
    `no screams`,
    `the nasty-neon of N.Y.`,
    `on your sweet soul`,
    `^g2 hat in my hand`,
  ],
  [
    // 9: "noun phrase, p",
    `in the woods`,
    `at Baffin's Bay`,
    `a dwelling house`,
    `in the social house`,
    `at the window`,
    `in the village`,
    `by the mountain side`,
    `at the village inn`,
    `in the ballroom`,
    `at the ballroom door`,
    `in the lighted hall`,
    `at ^g2o side`,
    `the place`,
    `at John Brown's coal mine`,
    `on the cold hard ground`,
    `in the top floor room`,
  ],
  [
    // 10: "noun phrase, d",
    `clothes all wet and muddy`,
    `no friends or relations`,
    `the only one`,
    `ten thousand pounds`,
    `mean ol' Stagolee`,
    `a bad ^g5`,
    `a bad ^g5o`,
    `the piercing air`,
    `the creaking sound of the runners`,
    `the sound of merry bells`,
    `^g1o lifeless form`,
    `that poor body`,
    `^g2 clothes out the door`,
    `the reason for it all`,
    `one true love`,
    `an eternity for two`,
    `a winters worth of rain`,
    `one true love`,
    `naked and grimy`,
    `silhouetted by fungus`,
    `a Tyrannical Futurist`,
    `^g2 face moved in pain`,
  ],
  [
    // 11: "noun phrase, w",
    `one night`,
    `twenty-one years`,
    `a mighty long time`,
    `before sunrise, tomorrow`,
    `thursday morning`,
    `one fine summer day`,
    `twelve o'clock`,
    `many pleasant winter's night`,
    `New Year's Eve`,
  ],
  [
    // 12: "noun phrase prep, a",
    // `with my dying breath`,
    // `for twenty-one year`,
    // `^g1 knew that ^g1o would drown`,
    // `no ^g5o may know`,
    // `from ^g2o brow`,
    // `around ^g2o neck`,
    // `^g2o head was found in the drivin' wheel`,
    // `a tear trinkled down`,
    // `^g1 can't keep a good one down`,
  ],
  [
    // 13: "noun phrase prep, h",
  ],
  [
    // 14: "noun phrase prep, t",
    // `on your sweet soul`,
    // `^g2 hat in my hand`,
  ],
  [
    // 15: "noun phrase prep, p",
    `down in the tavern`,
    `from ^g2o heart`,
    `from ^g2 heart`,
    `in the old churchyard`,
    `in the lone green valley`,
    `in this maiden's cottage`,
    `deep in ^g2o bosom`,
    `at Adams's Springs`,
    `in the frozen ocean`,
    `in mountains of ice`,
    `in ^g2 skin canoe`,
    `in the electric chair`,
    `by the mountain side`,
    `around ^g2 neck`,
    `around the mountain side`,
    `at the ballroom door`,
    `in to the lighted hall`,
    `by ^g2o side`,
    `in a cold grave`,
    `upon her grave`,
    `where she lay`,
    `by the waters edge`,
    `behind her`,
    `on a street with no name`,
    `in the caucasian suicide centre`,
  ],
  [
    // 16: "noun phrase prep, d",
    `without the love`,
    `in cold blood`,
    `a darlin loving wife`,
    `for five miles around ^g1`,
    `many miles away`,
    `in each hand`,
    `from each eye`,
    `like there's a pillow over ^g2o mouth`,
    `led by the shepherdess`,
    `^g2o hand was pressed whitely against the glass`,
    `covered by the autumn leaves`,
    `with no convictions`,
    `harmless, lonely`,
  ],
  [
    // 17: "noun phrase prep, w",
    `upon our wedding day`,
    `one night on the deep`,
    `in the month of May`,
    `the day Evalina died`,
    `it was two in the morning`,
    `on the night of the sacrifactions`,
  ],
  [
    // 18: "verb phrase",
    `tied a lover's knot`,
    `pleaded for ^g2o life`,
    `closed my eyes in death`,
    `always loved`,
    `never deceived ^g4o`,
    `will forgive`,
    `said "you'll be mine`,
    `looked down that railroad`,
    `kept right on waving`,
    `begged the governor`,
    `can't get a pardon`,
    `got a parole`,
    `counted on ^g4o, babe`,
    `rotted in prison`,
    `told no lies`,
    `brought ^g4o no money`,
    `did go`,
    `turned ^g4o around`,
    `saw little Omie's body go floating away`,
    `drew ^g4o to the bank`,
    `laid ^g4o on a plank`,
    `carried him to jail`,
    `would go on his bail`,
    `was homeward bound`,
    `fell asleep`,
    `dreamed a dream`,
    `thought it true`,
    `crossed the main`,
    `freely gave`,
    `spent a hundred dollars`,
    `was a bad ^g5o`,
    `was a bad ^g5`,
    `shot Billy the Lion`,
    `shot ^g4o down`,
    `spent a hundred dollars`,
    `lived`,
    `was young and fair`,
    `loved ^g2o daughter`,
    `had blue eyes`,
    `hung ^g2 hair down low`,
    `was wrecked at the four mile hill`,
    `made it home`,
    `spent ^g2 money to the last dime`,
    `told ^g4o how long`,
    `will have to wait`,
    `treated me like a dog`,
    `could not afford to lose`,
    `never had but one true love`,
    `will sit and weep`,
    `came into town`,
    `whistled loud and clearly`,
    `whistled and sang`,
    `charmed ^g2o heart`,
    `came tripping downstairs`,
    `drove along`,
    `was muddy`,
    `pulled the phone cord out of the wall`,
    `was never to be disturbed`,
    `retreated into death`,
    `was thrown on the highway`,
  ],
  [
    // 19: "verb phrase prep",
    `where the roses bloom and fade`,
    `the moon shone brightly`,
    `down by ^g2o side`,
    `the rain was pouring`,
    `^g1 watched the clouds pass by`,
    `over the hills they went`,
    `silence broke at last`,
    `much faster than before`,
    `words spoke never more`,
    `on that train`,
    `^g1 will sleep in the woods`,
  ],
  [
    // 20: "adverb",
    `slowly`,
    `silently`,
    `quietly`,
    `quickly`,
    `sadly`,
    `madly`,
  ],
  [
    // 21: "adjective",
    `quite`,
    `angry`,
    `sad`,
    `slow`,
  ],
  [
    // 22: "adjective phrase",
    `dig it wide and narrow`,
    `could grow no higher`,
    `in love`,
    `with hearts brave and true`,
    `as far as you can see`,
    `as fine as a city belle`,
    `quite warm`,
    `all bundled up`,
    `hard as stone`,
    `the whole day long`,
    `as any young man may`,
    `for twelve-month and a day`,
    `over five long miles`,
    `a dark spirited pluralist`,
  ],
  [
    // 23: "transitive verb",
    `pulled the curtain back`,
    `buried ^g4o`,
    `drew`,
    `counted`,
    `did murder`,
    `told ^g4o to meet ^g4`,
    `promised ^g4o money`,
    `kissed ^g4o`,
    `hugged ^g4s`,
    `pushed ^g4o in deep waters`,
    `searched for Omie`,
    `sent for John Lewis`,
    `brought ^g4o out before ^g4`,
    `killed ^g4o`,
    `stepped into the sleigh`,
    `cracked ^g2 whip`,
    `urged ^g2 steed`,
    `rode through`,
    `drove`,
    `stepped out`,
    `Reached for ^g2o hand`,
    `called ^g4o by ^g2o name again`,
    `took ^g2o hand in ^g3`,
    `bore ^g2o lifeless form`,
    `knelt down by ^g2o side`,
    `killed my Evaline`,
    `walked the track`,
    `carried ^g4o away`,
    `brought ^g4`,
    `threw ^g2o hat out the window`,
    `throwed ^g4o in the jail`,
    `eased ^g2o pain`,
    `adored ^g4o`,
    `caused the wild woods to ring`,
    `charmed ^g2o heart`,
    `asked for ^g2 lady`,
  ],
  [
    // 24: "intransitive verb",
    `got up`,
    `shall never get better`,
    `looked to the East`,
    `looked to the West`,
    `cried`,
    `gazed`,
    `mourned`,
    `burst out cryin'`,
    `died that day`,
    `grew a red, red rose`,
    `grew so awful high`,
    `strolled`,
    `wandered`,
    `sang above`,
    `grew angry`,
    `heard that train blow`,
    `must part`,
    `climbed up behind ^g4o`,
    `got on ^g2 pony`,
    `made no confession`,
    `sailed away`,
    `laughed`,
    `ran around`,
    `passed at six o'clock`,
    `came by at nine`,
    `hung down`,
    `didn't want ^g4o anymore`,
    `won't stay with ^g2o`,
    `hesitated`,
    `came home`,
    `drove along`,
    `gave up to the holy ghost`,
    `screamed ^g2 guts out from over the street`,
    `vomited out ^g2 doctrine`,
  ],
  [
    // 25: "dialogue phrase",
    `^g1 believe you're dying!`,
    `Oh yes, oh yes, I'm very sick.`,
    `Don't you remember not long ago?`,
    `Put ^g4o down and leave ^g4o there.`,
    `^g1 begged ^g4o to come and take ^g4 away.`,
    `Stagolee, please don't take my life?`,
    `What do ^g1 care about your two little babes and your darlin' loving' wife?`,
    `Stagolee, what you doin' in here?`,
    `My six-shooter never lied.`,
    `Hold up your head.`,
    `Dry up your eyes.`,
    `^g1 guess you forgot.`,
    `^g1 Know who's guilty.`,
    `Until ^g1 get back.`,
    `I seek a passage.`,
    `It's a dreadful night to go abroad.`,
    `You'll catch a deathly cold.`,
    `Oh no, oh no`,
    `^g1 never shall be seen.`,
    `Such a night as this ^g1 never knew.`,
    `These lines ^g1 scarce can hold.`,
    `I'm growing very cold.`,
    `It's ten long dreadful miles to go.`,
    `I'm growing warmer now.`,
    `^g1o said not a word.`,
    `^g2 own, bride, ^g1 never more shall know.`,
    `Oh who sits weeping on ^g2 grave.`,
    `'Tis ^g1, m'love, upon thy grave.`,
    `Who will not let ^g4 sleep.`,
    `Go saddle me ^g2 old grey steed.`,
    `^g1 have drove all day.`,
    `I will drive all night till ^g1 overtake my lady.`,
    `Tonight ^g1 lie on the damp cold ground.`,
    `A band of gypsies surrounds ^g4.`,
    `In the future, everything was up to itself.`,
    `The slashing of the fabric machine.`,
    `Everything and everyone died around him.`,
    `Suffering, healing and redemption.`,
    `You can never tell what an artist will do once he's peaked.`,
    `Scenes of a harsh life.`,
    `You go to the fields.`,
    `And you work all day.`,
    `Till way after dark, but you get no pay.`,
    `It's hard to be a renter on Penny's farm.`,
    `Now here's George Penny come into town.`,
    `With ^g2o wagon-load of peaches, not one of them sound.`,
    `^g1's got to have ^g2o money or somebody's check.`,
    `You pay him for a bushel, And you don't get a peck.`,
    `Then George Penny's renters, they come into town.`,
    `With their hands in their pockets, and their heads hanging down.`,
    `Your mortgage is due And ^g1 looking for my pay.`,
    `Goes down in ^g2o pocket with a trembling hand.`,
    `Can't pay you all but ^g1 will pay you what ^g1 can.`,
    `Then to the telephone the merchant makes a call.`,
    `They'll put you on the chain gang if you don't pay it all.`,
    `John Hardy was a desperate little man.`,
    `^g1 carried two guns every day.`,
    `^g1 shot down a man on that West Virginia line.`,
    `You ought a seen John Hardy getting away.`,
    `John Hardy stood in that old barroom.`,
    `So drunk that he could not see.`,
    `And a man walked up and took him by the arm.`,
    `^g1 said Johnny, come and go along with me Poor boy.`,
    `Johnny, come and walk along with me.`,
    `John Hardy stood in ^g2o old jail cell.`,
    `The tears running down from ^g2o eyes.`,
    `^g1 said ^g1 been the death of many a poor boy.`,
    `But my six-shooters never told a lie.`,
    `The first one to visit John Hardy in ^g2o cell.`,
    `Was a ^g5 girl dressed in blue.`,
    `She came down to that old jail cell.`,
    `She said Johnny, ^g1 been true to you God knows.`,
    `Johnny, ^g1 been true to you.`,
    `Will You Miss Me When I'm Gone?.`,
    `The next one to Visit John Hardy in ^g2o cell.`,
    `Was a ^g5 dressed in red.`,
    `She come down to that old jail cell.`,
    `^g1 said, Johnny, I had rather see you dead.`,
    `^g1 been to the East and ^g1 been to the West.`,
    `^g1 traveled this wide world around.`,
    `^g1 been to that river and ^g1 been baptized.`,
    `So take me to my burying ground.`,
    `you gotta be rich to kill somebody and get away with it.`,
    `You think you got that kind of dough?.`,
    `You think you got that kind of class?.`,
    `Down in the Willow garden.`,
    `Where me and my love did meet.`,
    `As we sat a-courtin' My love fell off to sleep.`,
    `^g1 had a bottle of Burgundy wine.`,
    `My love ^g2o did not know.`,
    `^g1 poisoned that ^g5o.`,
    `On the banks below.`,
    `^g1 drew a saber through her.`,
    `It was a bloody knife.`,
    `^g1 threw her in the river.`,
    `Which was a dreadful sign.`,
    `My father often told me money would set me free.`,
    `If ^g1 would murder that ^g5o.`,
    `Whose name was Rose Connolly.`,
    `My father sits at the cabin door.`,
    `Wiping ^g2o tear-dimmed eyes.`,
    `For ^g2o only son soon shall walk the scaffold.`,
    `My race is run, beneath the sun.`,
    `The scaffold now waits for me.`,
    `Whose name was Rose Connolly.`,
    `^g1 asked my love to take a walk.`,
    `To take a walk, just a little walk.`,
    `Down beside where the waters flow.`,
    `Down by the banks of the Ohio.`,
    `And only say that you'll be mine.`,
    `In no other's arms entwine.`,
    `Down by the banks.`,
    `^g1 held a knife against ^g2o breast.`,
    `As into my arms ^g2o pressed.`,
    `My love, don't you murder me!`,
    `^g1 am not prepared for eternity.`,
    `^g1 wandered home 'tween 12 and one.`,
    `My God, what have ^g1 done?`,
    `^g1 killed the only ^g5o ^g1 love.`,
    `^g1 would not take me for ^g2o bride.`,
  ],
];
const templates = [
  ...Array(7).fill(`^19\n^19\n^19\n^19`),
  `^14 ^g1 ^18\nWhere ^g1o ^12\nAnd when ^g1 ^17\nSaid, ^19`,
  `^19\n^g1 ^18\n^2`,
  `^19\n^5, ^9\n^g1o ^17 there`,
  `^g1 ^18, ^g1 ^18\n^g1 saw ^2 coming\nAnd ^18, ^19\n^g1 ^17`,
  `The more ^g1 ^18, the more ^g1 ^18\nUntil ^g1 ^18\nSayin', ^19\n^0`,
  `^g1 ^17\n^16\n^1 ^18\n^g1 ^18`,
  `^g1 ^17, ^9\n^g1 ^17,\n^9 ^g1 ^18\n^9 ^0`,
  `They ^18\n^16\nAnd it was there they ^12\n^0`,
  `^13 ^9\n^13\nThere was ^2\n^16`,
  `^5 ^g1 ^12\nFor ^2 ^12\nAnd ^9\n^2 ^17`,
  `^19\n^9 \nWhile ^g1 ^18, and ^12\n^11`,
  `^13 they ^18\nWith ^2 ^g1  ^18\nWith ^2 we ^18\n^1 ^17`,
  `^13 before ^g4o\n^g1 ^12\nBut ^9\n^g1 ^17`,
  `^19\nYou know ^g1 ^12\n^g1 ^12\nBut ^0, ^g1 ^12\nand ^12`,
  `^g1 ^12, ^g1 ^12\n^g1 ^12, ^1\n^g1o ^17 ^9\n^g1 ^17, ^2`,
  `^13 ^9\n^g1o ^12, ^2\n^19\n^19`,
  `^g1 ^17 and ^g1 ^12\n^9 ^3\n^19\n^19`,
  `^19\n^0, ^g1 ^12\n^19\n^19`,
  `^g1 ^17, ^12\n^g1 ^17 ^0\n^g1 ^17 \nAs ^2 rose ^11`,
  `T'was ^5 ^g1 ^12\n^g1 ^12, ^0\n^5\nAnd ^g1o ^12`,
  `^g1 ^17 and ^g1 ^17\n^4 ^17\nThen ^g1 ^17 ^9\nAnd ^17, ^0`,
  `^g1 ^12 but ^g1o ^17\n^2 ^12`,
  `^2 said ^19\n^g1o ^17, ^11\n^g1 ^12 and ^12\n^5 is ^5`,
  `^g1 ^18, ^13\n^g1 ^12, ^0\n^g1 ^12 ^16\nAnd ^g1 ^12, ^0`,
  `^2, ^2\n^g1 ^12, ^13\n^g1 ^12 babe and ^g1 ^12\n^2, ^g1 ^18, ^0`,
  `^g1 ^12, in ^2\n^g1 ^12 \nIf only ^g1 had ^2 \n^0\n^5 `,
  `^g1 ^17, ^2 ^g1 ^17, ^2\n^g1 ^17, ^2 ^g1 ^17, ^2\n^g1 ^17, ^2 ^g1 ^17, ^2\n^g1 ^17, ^4`,
  `^g1 ^12 and ^g1 ^12\n^g1o ^12, ^0\n^g1 ^12 ^13\n^13`,
  `^g1 ^12 and ^16\n^g1 ^12, ^5 \n^g1o ^12\n^g1 ^12, ^2\n^4\n^5 is ^5`,
];
