export const lookup = {
  0: "noun phrase, a",
  1: "noun phrase, h",
  2: "noun phrase, t",
  3: "noun phrase, p",
  4: "noun phrase, d",
  5: "noun phrase, w",
  6: "noun phrase prep, a",
  7: "noun phrase prep, h",
  8: "noun phrase prep, t",
  9: "noun phrase prep, p",
  10: "noun phrase prep, d",
  11: "noun phrase prep, w",
  12: "verb phrase",
  13: "verb phrase prep",
  14: "adverb",
  15: "adjective",
  16: "adjective phrase",
  17: "transitive verb",
  18: "intransitive verb",
  19: "dialogue phrase",
};

export const genders = [
  [
    ["he", "she"],
    ["his", "her"],
    ["his", "hers"],
    ["him", "her"],
    ["man", "woman"],
  ],
  [
    ["I", "you"],
    ["my", "your"],
    ["mine", "yours"],
    ["me", "you"],
    ["person", "friend"],
  ],
];

export const tags = [
  [
    // 6: "noun phrase, a",
    `for my heart now too is dyin!`,
    `to serve out my time`,
    `your farewell to me`,
    `the doctor came`,
  ],
  [
    // 7: "noun phrase, h",
    `a jealous lover`,
    `a beautiful maid`,
    `the governor`,
    `two boys`,
    `a hundred seamen`,
    `the jealous lover`,
    `the beautiful girl`,
    `the people`,
    `the eskimo`,
    `young folks`,
    `her father`,
    `the only child`,
    `a gypsy queen`,
    `Charlie`,
    `Charlotte`,
    `the prettiest girl`,
    `Evaline`,
    `a long tall mama`,
    `a sweet little woman`,
    `a hesitation' papa`,
    `a hesitation' mama`,
    `the doctors son`,
    `m'love`,
    `my sweetest love`,
    `poor William`,
    `the judge`,
    `John Lewis`,
    `Omie Wise`,
    `Stagolee`,
    `young Charlotte`,
    `m'love`,
    `^g2 sweetest love`,
    `^g2 true love`,
    `the gypsy`,
    `a lady`,
    `the servant`,
    `^g2o lord`,
    `^g2 lady`,
    `^g2 lord`,
  ],
  [
    // 8: "noun phrase, t",
    `^g2 pale corpse`,
    `^g2o pale corpse`,
    `a red rose and the briar`,
    `a briar`,
    `^g2 six shooter`,
    `the stars`,
    `the night`,
    `the birds`,
    `the fatal knife`,
    `the steam from the whistle`,
    `the smoke from the stack`,
    `best friends`,
    `the days`,
    `the nights`,
    `the minutes`,
    `the footsteps`,
    `the stars`,
    `prison bars`,
    `other fine things`,
    `the screams of little Omie`,
    `cruel hardships`,
    `the fate of franklin`,
    `my burden`,
    `my long-lost franklin`,
    `a suit of clothes`,
    `the sun`,
    `bright blue eyes`,
    `^g2o heart`,
    `the sleigh`,
    `^g2 silken coat`,
    `cloak and bonnet`,
    `the frozen snow`,
    `the frozen air`,
    `these frozen words`,
    `the silence`,
    `the frosty ice`,
    `the frosty air`,
    `the glittering cold starlight`,
    `^g2o hand`,
    `the cold stars`,
    `a frozen corpse`,
    `the bitter tears`,
    `^g2 thoughts`,
    `the longest train`,
    `that train`,
    `the longest day`,
    `the longest night`,
    `the long steel rail`,
    `transportation`,
    `a hesitatin' blues`,
    `the headlight`,
    `^g2 hat in my hand`,
    `the dead`,
    `a bottle of wine`,
    `the gypsy daisy`,
    `^g2 old grey steed`,
    `the water`,
    `a feather bed`,
    `a band of gypsies`,
  ],
  [
    // 9: "noun phrase, p",
    `the woods`,
    `Baffin's Bay`,
    `a dwelling house`,
    `father's cot`,
    `a social house`,
    `the window`,
    `a village`,
    `the mountain side`,
    `the village inn`,
    `the ballroom`,
    `the ballroom door`,
    `the mantle from ^g2o brow`,
    `the lighted hall`,
    `^g2o side`,
    `the place`,
    `John Brown's coal mine`,
    `the cold hard ground`,
  ],
  [
    // 10: "noun phrase, d",
    `clothes all wet and muddy`,
    `no friends or relations`,
    `the only one`,
    `ten thousand pounds`,
    `mean ol' Stagolee`,
    `a bad ^g5`,
    `a bad ^g5o`,
    `the piercing air`,
    `the creaking sound the runners made`,
    `the sound of merry bells`,
    `^g1o lifeless form`,
    `that poor body`,
    `^g2 clothes out the door`,
    `the reason for it all`,
    `aint the doctor`,
    `a winters worth of rain`,
    `one true love`,
    `an eternity for two`,
    `a winters worth of rain`,
    `one true love`,
  ],
  [
    // 11: "noun phrase, w",
    `one night`,
    `twenty-one years`,
    `a mighty long time`,
    `before sunrise, tomorrow`,
    `thursday morning`,
    `one fine summer day`,
    `twelve o'clock`,
    `many pleasant winter's night`,
    `new years eve`,
    `a merry ball tonight`,
    `some day`,
  ],
  [
    // 12: "noun phrase prep, a",
    `with my dying breath`,
    `for twenty-one year`,
    `^g1 knew that ^g1o would drown`,
    `no ^g5o may know`,
    `from ^g2o brow`,
    `around ^g2o neck`,
    `^g2o head was found in the drivin' wheel`,
  ],
  [
    // 13: "noun phrase prep, h",
  ],
  [
    // 14: "noun phrase prep, t",
    `on your sweet soul`,
    `^g2 hat in my hand`,
  ],
  [
    // 15: "noun phrase prep, p",
    `down in the tavern`,
    `from ^g2o heart`,
    `from ^g2 heart`,
    `in the old churchyard`,
    `in the lone green valley`,
    `in this maiden's cottage`,
    `deep in ^g2o bosom`,
    `at Adams's Springs`,
    `in the frozen ocean`,
    `in mountains of ice`,
    `in ^g2 skin canoe`,
    `in the electric chair`,
    `by the mountain side`,
    `around ^g2 neck`,
    `to the sleigh`,
    `around the mountain side`,
    `to the ballroom door`,
    `in to the lighted hall`,
    `by ^g2o side`,
    `^g2 back to the wall`,
    `in a hollow log`,
    `in a cold grave`,
    `upon her grave`,
    `where she lay`,
    `by the waters edge`,
    `behind her`,
  ],
  [
    // 16: "noun phrase prep, d",
    `without the love`,
    `in cold blood`,
    `a darlin loving wife`,
    `for five miles around ^g1`,
    `many miles away`,
    `in each hand`,
    `from each eye`,
  ],
  [
    // 17: "noun phrase prep, w",
    `upon our wedding day`,
    `one night on the deep`,
    `in the month of May`,
  ],
  [
    // 18: "verb phrase",
    `tied a lover's knot`,
    `pleaded for ^g2o life`,
    `closed my eyes in death`,
    `always loved`,
    `never deceived`,
    `will forgive`,
    `said "you'll be mine"`,
    `looked down that railroad`,
    `kept right on waving`,
    `be true love`,
    `begged the governor`,
    `can't get a pardon`,
    `got a parole`,
    `counted on you, babe`,
    `rotted in prison`,
    `told no lies`,
    `brought ^g4o no money`,
    `did go`,
    `turned ^g4o around`,
    `saw little Omie's body go floating away`,
    `drew ^g4o to the bank`,
    `laid ^g4o on a plank`,
    `carried him to jail`,
    `would go on his bail`,
    `was homeward bound`,
    `fell asleep`,
    `dreamed a dream`,
    `thought it true`,
    `crossed the main`,
    `freely gave`,
    `spent a hundred dollars`,
    `was a bad ^g5o`,
    `was a bad ^g5`,
    `shot Billy the Lion`,
    `shot ^g4o down`,
    `stole his Stetson hat`,
    `got two little babes`,
    `spent a hundred dollars`,
    `lived`,
    `kept`,
    `was young and fair`,
    `loved ^g2o daughter`,
    `was low`,
    `ever did see`,
    `eyes were blue`,
    `cheeks were brown`,
    `hair it hung way down`,
    `was wrecked at the four mile hill`,
    `the day Evalina died`,
    `make it home`,
    `spent ^g2 money to the last dime`,
    `tell ^g4 how long`,
    `will have to wait`,
    `can get away now`,
    `come hear mama`,
    `can get you now`,
    `treat me like a dog`,
    `payin' a rose on me`,
    `can't afford to lose`,
    `never had but one true love`,
    `will sit and weep`,
    `will i see my love true`,
    `come into town`,
    `whistled loud and clearly`,
    `whistled and sang`,
    `charmed the heart`,
    `came tripping downstairs`,
    `gone with the gypsy daisy`,
    `drove along`,
    `was muddy`,
    `a tear trinkled down`,
  ],
  [
    // 19: "verb phrase prep",
    `where the roses bloom and fade`,
    `the moon shone brightly`,
    `down by ^g2o side`,
    `the rain was pouring`,
    `watch the sleighs pass by,`,
    `over the hills they went,`,
    `silence broke at last`,
    `much faster than before`,
    `words spoke never more`,
    `a frozen corpse`,
    `on that train and gone`,
    `a-fightin' all the time`,
    `will sleep in the woods`,
    `to drink`,
  ],
  [
    // 20: "adverb",
    `slowly`,
    `silently`,
    `quietly`,
    `quickly`,
    `sadly`,
    `madly`,
  ],
  [
    // 21: "adjective",
    `quite`,
    `angry`,
    `sad`,
    `slow`,
  ],
  [
    // 22: "adjective phrase",
    `dig it wide and narrow`,
    `could grow no higher`,
    `in love`,
    `with hearts brave and true`,
    `as far as you can see`,
    `as fine as a city belle`,
    `quite warm`,
    `all bundled up`,
    `hard as stone`,
    `the whole day long`,
    `as any young man may`,
    `for twelve-month and a day`,
    `three four nevermore`,
    `for twelve-month and a day`,
    `over five long miles`,
  ],
  [
    // 23: "transitive verb",
    `pulled the curtain back`,
    `buried ^g4o`,
    `drew`,
    `counted`,
    `did murder`,
    `told ^g4o to meet ^g4`,
    `promised ^g4o money`,
    `kissed ^g4o`,
    `hugged ^g4o`,
    `pushed ^g4o in deep waters`,
    `searched for Omie`,
    `threw the net around ^g4o`,
    `sent for John Lewis`,
    `brought ^g4o out before ^g4`,
    `killed ^g4`,
    `would gather there`,
    `liked to see ^g2o dressed`,
    `joy beamed`,
    `had a silken scarf`,
    `stepped in to the sleigh`,
    `cracked ^g2 whip`,
    `urged ^g2 steed`,
    `rode through`,
    `drove up`,
    `stepped out`,
    `reached ^g2 hand`,
    `asked ^g4o once`,
    `asked ^g4o twice`,
    `asked ^g4o three times o'er`,
    `called ^g4o by ^g4o name again`,
    `took ^g2o hand in ^g2o`,
    `tore the mantle from ^g2o brow`,
    `bore ^g2o lifeless form`,
    `knelt down by ^g2o side`,
    `wrapped ^g2 arms`,
    `killed my Evaline`,
    `walked the track`,
    `carried ^g4 away`,
    `brought ^g4 here`,
    `threw ^g2 hat out the window`,
    `will get another mama`,
    `throwed ^g4 in the jail`,
    `paid' a rose on ^g4`,
    `can ease ^g2o pain`,
    `found a hesitatin' mama`,
    `Adored ^g2o`,
    `the dead began to speak`,
    `caused the wild woods to ring`,
    `charmed the heart`,
    `asked for ^g2 lady`,
    `spied ^g2 lady`,
  ],
  [
    // 24: "intransitive verb",
    `got up`,
    `shall never get better`,
    `looked to the East`,
    `looked to the West`,
    `cried`,
    `gazed`,
    `mourned`,
    `burst out cryin'`,
    `died for me today`,
    `grew a red, red rose`,
    `grew so awful high`,
    `strolled`,
    `wandered`,
    `sang above`,
    `grew angry`,
    `heard that train blow`,
    `must part`,
    `climbed up behind ^g4o`,
    `got on ^g2 pony`,
    `made no confession`,
    `sailed away`,
    `laughed`,
    `shone`,
    `ran around`,
    `passed at six o'clock`,
    `came by at nine`,
    `hung down`,
    `don't want ^g4 anymore`,
    `a-cussin' and a-fussin'`,
    `won't stay with you`,
    `must ^g1 hesitate`,
    `came home`,
    `drove along`,
  ],
  [
    // 25: "dialogue phrase",
    `"^g1 believe you're dying!"`,
    `"Oh yes, oh yes, I'm very sick"`,
    `"Don't you remember not long ago?"`,
    `"Put ^g4o down and leave ^g4o there"`,
    `"^g1 beg you come and take ^g4o away"`,
    `"Stagolee, please don't take my life?"`,
    `"What do ^g1 care about your two little babes and your darlin' loving' wife?"`,
    `"Stagolee, what you doin' in here?"`,
    `"My six-shooter never lied"`,
    `"Hold up your head"`,
    `"Dry up your eyes"`,
    `"^g1 guess you forgot"`,
    `"^g1 Know who's guilty"`,
    `"Until ^g1 get back"`,
    `"^g1 seek a passage"`,
    `"Oh daughter dear", ^g2 mother said, "Fold this blanket around you"`,
    `"It's a dreadful night to go abroad"`,
    `"You'll catch your deathly cold"`,
    `"Oh no oh no", the daughter said`,
    `"^g1 never shall be seen."`,
    `"Such a night as this ^g1 never knew, These lines ^g1 scarce can hold."`,
    `"I'm growing very cold."`,
    `"It's ten long dreadful miles to go, And it's o'er ice and snow."`,
    `"How fast the frosty ice Keeps gathering on ^g1o brow."`,
    `"I'm growing warmer now."`,
    `"Why sit you there like a monument, when within is power to stir."`,
    `^g1o said not a word.`,
    `"^g2 own, bride, ^g1 never more shall know."`,
    `"^g1 am growing warmer now."`,
    `"Oh who sits weeping on ^g2 grave And will not let ^g4 sleep?"`,
    `"'Tis ^g1, m'love, upon thy grave"`,
    `"Who will not let ^g4 sleep"`,
    `"^g1o has gone with the gypsy daisy."`,
    `"Go saddle me ^g2 old grey steed,"`,
    `"^g1 have drove all day and ^g1I will drive all night till ^g1 overtake my lady."`,
    `"Tonight ^g1 lie on the damp cold ground,`,
    `"A band of gypsies surrounds ^g4."`,
  ],
];
