export const lookup = {
  0: "noun, a",
  1: "noun, h",
  2: "noun, t",
  3: "noun, p",
  4: "noun, d",
  5: "noun, w",
  6: "noun phrase, a",
  7: "noun phrase, h",
  8: "noun phrase, t",
  9: "noun phrase, p",
  10: "noun phrase, d",
  11: "noun phrase, w",
  12: "noun phrase prep, a",
  13: "noun phrase prep, h",
  14: "noun phrase prep, t",
  15: "noun phrase prep, p",
  16: "noun phrase prep, d",
  17: "noun phrase prep, w",
  18: "verb phrase",
  19: "verb phrase prep",
  20: "adverb",
  21: "adjective",
  22: "adjective phrase",
  23: "transitive verb",
  24: "intransitive verb",
  25: "dialogue phrase",
};

export const genders = [
  ["he", "she"],
  ["his", "her"],
  ["his", "hers"],
  ["him", "her"],
  ["man", "woman"],
];

export const tags = [
  [
    // 0: "noun, a",
  ],
  [
    // 1: "noun, h",
    "poor William",
    "the judge",
    "John Lewis",
    "Omie Wise",
    "Stagolee",
  ],
  [
    // 2: "noun, t",
    "a briar",
  ],
  [
    // 3: "noun, p",
  ],
  [
    // 4: "noun, d",
  ],
  [
    // 5: "noun, w",
    "the day",
  ],
  [
    // 6: "noun phrase, a",
    "for my heart now too is dyin!",
    "to serve out my time",
    "your farewell to me",
  ],
  [
    // 7: "noun phrase, h",
    "a jealous lover",
    "a beautiful maid",
    "the governor",
    "two boys",
    "a hundred seamen",
  ],
  [
    // 8: "noun phrase, t",
    "^g2 pale corpse",
    "^g2a pale corpse",
    "a red rose and the briar",
    "the stars",
    "the jealous lover",
    "the beautiful girl",
    "the night",
    "the birds",
    "the fatal knife",
    "the steam from the whistle",
    "the smoke from the stack",
    "best friends",
    "the days",
    "the nights",
    "the minutes",
    "the footsteps",
    "the stars",
    "prison bars",
    "other fine things",
    "the screams of little Omie",
    "the people",
    "cruel hardships",
    "the eskimo",
    "the fate of Franklin",
    "my burden",
    "my long-lost Franklin",
    "a suit of clothes",
  ],
  [
    // 9: "noun phrase, p",
    "the woods",
    "baffin's bay",
  ],
  [
    // 10: "noun phrase, d",
    "a million",
    "clothes all wet and muddy",
    "no friends or relations",
    "the only one",
    "ten thousand pounds",
    "mean ol' Stagolee",
    "a bad ^g5",
  ],
  [
    // 11: "noun phrase, w",
    "one night",
    "twenty-one years",
    "a mighty long time",
    "before sunrise, tomorrow",
    "thursday morning",
    "one fine summer day",
    "twelve o'clock",
  ],
  [
    // 12: "noun phrase prep, a",
    "with my dying breath",
    "for twenty-one year",
    "^g1 knew that ^g1a would drown",
    "no ^g5 may know",
  ],
  [
    // 13: "noun phrase prep, h",
  ],
  [
    // 14: "noun phrase prep, t",
    "on your sweet soul",
  ],
  [
    // 15: "noun phrase prep, p",
    "the place",
    "down in the tavern",
    "from ^g4 heart",
    "from ^g4a heart",
    "in the old churchyard",
    "in the lone green valley",
    "in this maiden's cottage",
    "deep in ^g4 bosom",
    "at Adams's Springs",
    "in the frozen ocean",
    "in mountains of ice",
    "in ^g2 skin canoe",
    "in the electric chair",
  ],
  [
    // 16: "noun phrase prep, d",
    "without the love",
    "in cold blood",
    "a darlin loving wife",
  ],
  [
    // 17: "noun phrase prep, w",
    "upon our wedding day",
    "one night on the deep",
    "in the month of May",
  ],
  [
    // 18: "verb phrase",
    "tied a lover's knot",
    "pleaded for ^g2a life",
    "closed my eyes in death",
    "always loved",
    "never deceived",
    "will forgive",
    "said “you'll be mine”",
    "looked down that railroad",
    "kept right on waving",
    "be true love",
    "begged the governor",
    "can't get a pardon",
    "got a parole",
    "counted on you, babe",
    "rotted in prison",
    "told no lies",
    "brought ^g2a no money",
    "did go",
    "turned ^g2a around",
    "saw little Omie's body go floating away",
    "drew ^g2a to the bank",
    "laid ^g2a on a plank",
    "carried him to jail",
    "would go on his bail",
    "was homeward bound",
    "fell asleep",
    "dreamed a dream",
    "thought it true",
    "crossed the main",
    "freely gave",
    "spent a hundred dollars",
    "was a bad ^g5",
    "shot Billy the Lion",
    "shot ^g4 down",
    "stole his Stetson hat",
    "got two little babes",
    "spent a hundred dollars",
  ],
  [
    // 19: "verb phrase prep",
    "where the roses bloom and fade",
    "the moon shone brightly",
    "down by ^g2 side",
    "the rain was pouring",
  ],
  [
    // 20: "adverb",
    "slowly",
  ],
  [
    // 21: "adjective",
    "poor little",
    "quite",
  ],
  [
    // 22: "adjective phrase",
    "dig it wide and narrow",
    "could grow no higher",
    "in love",
    "With hearts brave and true",
    "As far as you can see",
  ],
  [
    // 23: "transitive verb",
    "pulled the curtain back",
    "buried ^g4",
    "drew",
    "counted",
    "did murder",
    "told ^g2a to meet ^g4",
    "promised ^g2a money",
    "kissed ^g2a",
    "hugged ^g2a",
    "pushed ^g2a in deep waters",
    "searched for Omie",
    "threw the net around ^g2a",
    "sent for John Lewis",
    "brought her out before ^g4",
    "killed ^g4",
  ],
  [
    // 24: "intransitive verb",
    "got up",
    "shall never get better",
    "looked to the East",
    "looked to the West",
    "cried",
    "gazed",
    "mourned",
    "burst out cryin'",
    "died for me today",
    "grew a red, red rose",
    "grew so awful high",
    "strolled",
    "wandered",
    "sang above",
    "grew angry",
    "heard that train blow",
    "must part",
    "climbed up behind ^g4",
    "got on ^g2 pony",
    "made no confession",
    "sailed away",
  ],
  [
    // 25: "dialogue phrase",
    '"I believe you\'re dying!"',
    '"Oh yes, oh yes, I\'m very sick"',
    '"Don\'t you remember not long ago?"',
    '"Put ^g4 down and leave ^g4 there"',
    '"I beg you come and take ^g4 away"',
  ],
];
