// 0 - Noun
// 1 - Noun Phrase
// 2 - Noun Phrase Prep
// 3 - Verb Phrase
// 4 - Verb Phrase Prep
// 5 - Adverb
// 6 - Adjective
// 7 - Adjective Phrase
// 8 - Transitive Verb
// 9 - Intransitive verb
// 10 - Dialogue phrase

export const tags = [
  [
    // Noun
    `the day`,
    `poor William`,
    `him`,
    `her`,
    `a briar`,
    `today`,
    `the judge`,
    `John Lewis`,
    `Omie Wise`,
    `Stagolee`,
  ],
  [
    // Noun Phrase
    `his pale corpse`,
    `for my heart now too is dyin!`,
    `in the old churchyard,`,
    `a red rose and the briar`,
    `a jealous lover`,
    `a beautiful maid`,
    `one night`,
    `the stars`,
    `the jealous lover`,
    `the night birds`,
    `the beautiful girl`,
    `the fatal knife`,
    `the woods`,
    `twenty-one years`,
    `a mighty long time`,
    `to serve out my time`,
    `your farewell to me`,
    `the steam from the whistle`,
    `the smoke from the stack`,
    `best friends`,
    `the governor`,
    `before sunrise, tomorrow`,
    `the days`,
    `the nights`,
    `the minutes`,
    `the footsteps`,
    `the stars`,
    `a million`,
    `prison bars`,
    `other fine things`,
    `the screams of little Omie`,
    `a thursday morning`,
    `the people`,
    `two boys`,
    `one fine summer day`,
    `clothes all wet and muddy`,
    `no friends or relations`,
    `a hundred seamen`,
    `cruel hardships`,
    `the eskimo`,
    `the only one`,
    `baffin's bay`,
    `the fate of Franklin`,
    `my burden`,
    `my long-lost Franklin`,
    `ten thousand pounds`,
    `a suit of clothes`,
    `mean ol' Stagolee`,
    `a bad man`,
    `twelve o'clock`,
  ],
  [
    // Noun Phrase Prep
    `the place`,
    `without the love`,
    `down in the tavern`,
    `from his heart,`,
    `from her heart`,
    `in the lone green valley`,
    `In this maiden's cottage`,
    `upon our wedding day`,
    `deep in her bosom`,
    `with my dying breath`,
    `for twenty-one years`,
    `on your sweet soul`,
    `at Adams's Springs`,
    `he knew that she would drown`,
    `one night on the deep`,
    `in the month of May`,
    `in the frozen ocean`,
    `In mountains of ice`,
    `in his skin canoe`,
    `in cold blood`,
    `In the electric chair`,
    `a darlin loving wife`,
    `no man may know`,
  ],
  [
    // Verb Phrase
    `tied a lover's knot`,
    `pleaded for her life`,
    `closed my eyes in death`,
    `always loved`,
    `never deceived`,
    `will forgive`,
    `said you'll be mine`,
    `looked down that railroad`,
    `kept right on waving`,
    `be true love`,
    `hold up your head`,
    `dry up your eyes`,
    `begged the governor`,
    `can't get a pardon`,
    `got a parole`,
    `counted on you, babe`,
    `guess you forgot`,
    `know who's guilty`,
    `rotted in prison`,
    `told no lies`,
    `brought her no money`,
    `did go`,
    `turned her around`,
    `saw little Omie's body go floating away`,
    `drew her to the bank`,
    `laid her on a plank`,
    `carried him to jail`,
    `would go on his bail`,
    `was homeward bound`,
    `fell asleep`,
    `dreamed a dream`,
    `thought it true`,
    `seek a passage`,
    `crossed the main`,
    `freely gave`,
    `spent a hundred dollars`,
    `was a bad man`,
    `shot Billy the Lion`,
    `shot him down`,
    `stole his Stetson hat`,
    `got two little babes`,
    `spent a hundred dollars`,
  ],
  [
    // Verb Phrase Prep
    `where the roses bloom and fade`,
    `the moon shone brightly`,
    `down by his side`,
    `until I get back`,
    `the rain was pouring`,
  ],
  [
    // Adverb
    `slowly`,
  ],
  [
    // Adjective
    `poor little`,
    `quite`,
  ],
  [
    // Adjective Phrase
    `dig it wide and narrow`,
    `could grow no higher`,
    `in love`,
    `hearts brave and true`,
    `far as you can see`,
  ],
  [
    // Transitive Verb
    `pulled the curtain back`,
    `drew`,
    `counted`,
    `did murder`,
    `told her to meet him`,
    `promised her money`,
    `kissed her`,
    `hugged her`,
    `pushed her in deep waters`,
    `searched for Omie`,
    `threw their net around her`,
    `sent for John Lewis`,
    `brought her out before him`,
    `killed him`,
  ],
  [
    // Intransitive verb
    `got up`,
    `shall never get better`,
    `looked to the East`,
    `looked to the West`,
    `cried`,
    `gazed`,
    `mourned`,
    `burst out cryin'`,
    `died for me today`,
    `grew a red, red rose`,
    `grew so awful high`,
    `strolled`,
    `wandered`,
    `sang above`,
    `grew angry`,
    `heard that train blow`,
    `must part`,
    `climbed up behind him`,
    `got on his pony`,
    `made no confession`,
    `sailed away`,
  ],
  [
    // Dialogue phrase
    `"I believe you're dying!"`,
    `"Oh yes, oh yes, I'm very sick"`,
    `"Don't you remember not long ago?"`,
    `"Put him down and leave him there"`,
    `"I beg you come and take him away"`,
    `"Stagolee, please don't take my life?"`,
    `"What do I care about your two little babes and your darlin' loving' wife?"`,
    `"Stagolee, what you doin' in here?"`,
    `"My six-shooter never lied"`,
  ],
];
